[WIP] Implement express backend
sentry-demos/application-monitoring pull request #33
Opened 2021-09-23 17:57 UTC by cstavitsky

2021-09-27 14:45 UTC, thinkocapo requested changes
Can you run
```
rm -rf express/node_modules
echo 'express/node_modules' >> .gitignore
## or 
echo '**/node_modules' >> .gitignore
```
basically delete express/node_modules, then commit this change, and reflect in gitignore that we want to ignore node_modules. (if you forget tgitignore then it will commit node_modules all over again)

and then push your changes to github, and this should remove the 400k committed node_modules from the github repo.

then I can review. right now I have to scroll past 4,000 changed files, the website started freezing on me.

2021-09-27 16:20 UTC, cstavitsky commented
@thinkocapo yep, I'll go ahead and take care of that. My bad - assumed that everything in `node_modules/` were files we'd want to commit.

2021-09-27 16:26 UTC, cstavitsky commented on express/server.js
>    console.log(`Server listening on port ${PORT}...`);
Note to self: update this to default to port `8081`!

2021-10-13 19:11 UTC, cstavitsky commented on .gitignore
> +flask/app.yaml
This could also just be `**/app.yaml` if we expect to add more backend other than express and springboot 🤷

2021-11-10 16:30 UTC, thinkocapo approved these changes

2021-11-10 16:30 UTC, merged